//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeApplication.Entities.Concrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masalar
    {
        public int Id { get; set; }
        public int MasaNo { get; set; }
        public Nullable<int> Kat { get; set; }
        public Nullable<int> GarsonID { get; set; }
        public int Statu { get; set; }
    }
}
