//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeApplication.Entities.Concrate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int Id { get; set; }
        public int MasaID { get; set; }
        public int UrunID { get; set; }
        public int Adet { get; set; }
        public int Tutar { get; set; }
        public int GarsonID { get; set; }
        public int Statu { get; set; }
    }
}
